# Theme
THEME = "Darkgray 5"
# Window size
WINDOWSWIDTH = 1408
WINDOWSHEIGHT = 950
# Column size
FIXEDCOLUMNWIDTH = 655
FIXEDCOLUMNHEIGHT = 120
COLUMNWIDTH = 630
COLUMNHEIGHT = 200
BUTTONHEIGHT = 1
# Content size
FIRSTTEXTWIDTH = 10
SECONDTEXTWIDTH = 7
INPUTWIDTH = 25
FULLWIDTH = INPUTWIDTH * 2 + SECONDTEXTWIDTH + 2
# Duration size
STARTWIDTH = 10
MONTHWIDTH = 4
YEARWIDTH = 4
DDWIDTH = 4
YEARINPUTWIDTH = 5
ENDWIDTH = 7
PREVIEWWIDTH = 7
# Description size
DESCRIPTIONWIDTH = 49
DESCRIPTIONREMOVEBUTTONWIDTH = 10
# Button size
REMOVEBUTTONWIDTH = 8
ADDBUTTONWIDTH = 6
BUTTONHEIGHT = 1
# Duration Selection
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
# Version
VERSION = "1.0"
# Number of fields
HEADINGSFIELD = 6
OBJECTIVEFIELD = 1
EDUCATIONFIELD = 9
SIDEPROJECTFIELD = 8
EXPERIENCEFIELD = 9
SKILLSFIELD = 3
# Keys to clear
KEYS_TO_CLEAR = ["NAME", "NICKNAME", "TELEPHONE", "EMAIL", "GITHUBLINK", "WEBLINK", "OBJECTIVE",
                 ("EDUCATION_NAME", 0), ("EDUCATION_DEGREE", 0), ('EDUCATION_START_MON', 0), 
                 ('EDUCATION_START_YEAR', 0), ('EDUCATION_END_MON', 0), ('EDUCATION_END_YEAR', 0),
                 ("EDUCATION_START", 0), ("EDUCATION_END", 0), ("EDUCATION_LIST", 0, 0), 
                 ("PJ_NAME", 0), ('PJ_START_MON', 0), ('PJ_START_YEAR', 0), ('PJ_END_MON', 0),
                 ('PJ_END_YEAR', 0), ("PJ_START", 0), ("PJ_END", 0), ("PJ_LIST", 0, 0), 
                 ("EXP_NAME", 0), ("EXP_SUBTITLE", 0), ('EXP_START_MON', 0), ('EXP_START_YEAR', 0),
                 ('EXP_END_MON', 0), ('EXP_END_YEAR', 0), ("EXP_START", 0), ("EXP_END", 0), 
                 ("EXP_LIST", 0, 0), ("SKILL_CATEGORY", 0), ("SKILL_LIST", 0)]
